---
title: "Laboratório 3 - Dados Relacionais e Joins"
author: "Pedro José"
format: pdf
editor: visual
---

```{r}
library(tidyverse)
library(leaflet)
```

```{r}
#importando os 3 arquivos
flights <- read_csv("flights.csv")
airlines <- read_csv("airlines.csv")
airports <- read_csv("airports.csv")
```

```{r}
#selecionando as colunas desejadas 
airports <- airports %>%
  select(IATA_CODE, CITY, STATE, LATITUDE, LONGITUDE)

flights <- flights %>%
  select(DESTINATION_AIRPORT, ARRIVAL_DELAY)

glimpse(airports)
glimpse(flights)
```

```{r}
# Definir o tamanho do chunk (1 milhão de linhas)
chunk_size <- 1000000

# Ver quantas linhas tem o flights
total_linhas <- nrow(flights)

# Ver o total de linhas
total_linhas
```

```{r}
#Resolvendo a c,d,e,f
library(readr)

#definindo a função que processa cada chunk, 
processar_chunk <- function(chunk, pos) {
  chunk %>%
    select(DESTINATION_AIRPORT, ARRIVAL_DELAY) %>%   
    filter(!str_starts(DESTINATION_AIRPORT, "1")) %>%
    drop_na() %>%
    group_by(DESTINATION_AIRPORT) %>%
    summarise(
      soma_atraso = sum(ARRIVAL_DELAY, na.rm = TRUE),
      n = n()
    )
}

#lendo e processando em chunks de 1 milhão cada 

resultados <- read_csv_chunked(
  "flights.csv",
  callback = DataFrameCallback$new(processar_chunk),
  chunk_size = 1000000
)


#calculando a média final por aeroporto
media_atraso <- resultados %>%
  group_by(DESTINATION_AIRPORT) %>%
  summarise(
    soma_total = sum(soma_atraso),
    n_total = sum(n),
    media_atraso = soma_total / n_total
  )

```

```{r}
#incluindo city e state na tabela flights
# coluna chave de flights = Destination_airport
#coluna chave de airports = IATA_Code


flights_sem_airport <- anti_join(flights, airports, by = c("DESTINATION_AIRPORT" = "IATA_CODE"))

flights <- flights %>%
  left_join(airports, by = c("DESTINATION_AIRPORT" = "IATA_CODE"))

glimpse(flights)
```

```{r}
#Quantos aeroportos tem por estado? 
aero_por_estado <- airports %>%
  group_by(STATE) %>% 
  summarise(num_aero = n()) %>% #esse n() equivale ao nrow(), mas                                      dentro do summarise usamos n()
  arrange(num_aero)
  
head(aero_por_estado)
```

```{r}
mapa_de_atrasos <- media_atraso %>%
  left_join(airports, by = c("DESTINATION_AIRPORT" = "IATA_CODE"))

glimpse(mapa_de_atrasos)
```

```{r}
#Criando o mapa
#this <- leaflet(mapa_de_atrasos) %>%
#  addTiles() %>%
# addMarkers(
#    lng = ~LONGITUDE,
#    lat = ~LATITUDE,
#    popup = ~paste(
#      "Aeroporto:", DESTINATION_AIRPORT, "<br>",
#      "Cidade:", CITY, "<br>",
#      "Estado:", STATE, "<br>",
#      "Atraso médio:", round(media_atraso, 2), "minutos"
#    )
#  )

# Exibir o mapa
#this
```




```{r}
#Horário
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

